org: filipw01
app: utilities
service: vaccine-check-auth
frameworkVersion: '2'

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - "ses:SendEmail"
          Resource:
            arn:aws:ses:eu-central-1:857990243218:identity/wachowiakf@gmail.com
        - Effect: 'Allow'
          Action:
            - "dynamodb:PutItem"
          Resource:
            arn:aws:dynamodb:*:*:table/vaccineCheck

resources:
  Resources:
    vaccineCheck:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: vaccineCheck
        AttributeDefinitions:
          - AttributeName: ttl
            AttributeType: N
        KeySchema:
          - AttributeName: ttl
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

functions:
  vaccine_check_auth:
    handler: index.handler
    memorySize: 1024
    timeout: 60
    maximumRetryAttempts: 0
    events:
      - schedule: rate(11 hours)
